---

# Evaluate whether to use e4s repositories or not
- name: Ensure 'sap_netweaver_ha_pacemaker_repos' exists and points to the correct repository list
  set_fact:
    sap_netweaver_ha_pacemaker_repos:
      "{{ (sap_netweaver_ha_pacemaker_use_e4s) | ternary(sap_netweaver_ha_pacemaker_e4s_repos, sap_netweaver_ha_pacemaker_standard_repos) }}"

- name: Ensure required repos for RHEL HA are enabled
  rhsm_repository:
    name: "{{ sap_netweaver_ha_pacemaker_repos }}"
    state: enabled
