#STOLEN FROM sap-hana-ha-pacemaker TODO FIX
- name: Allow concurrent fencing
  command: pcs property set concurrent-fencing=true
  run_once: true

- name: Set fencing timeout
  command: pcs property set stonith-timeout=900
  run_once: true

- name: Create password script
  copy:
    dest: "{{ sap_netweaver_ha_pacemaker_fencing_device.password_file }}"
    content: 'echo "{{ sap_netweaver_ha_pacemaker_fencing_device.pwd }}"'
    mode: 0700

- name: Enable stonith
  command: pcs property set stonith-enabled=true
  register: stonith
  changed_when: "'error' not in stonith.stdout"
  run_once: true

- name: Set password fragment
  set_fact:
    password_frag: "passwd={{ sap_netweaver_ha_pacemaker_fencing_device.pwd }}"
  when:
    - not( sap_netweaver_ha_pacemaker_fencing_device.password_file )

- name: Set password fragment
  set_fact:
    password_frag: "passwd_script={{ sap_netweaver_ha_pacemaker_fencing_device.password_file }}"
  when:
    - sap_netweaver_ha_pacemaker_fencing_device.password_file

- name: Create password script
  copy:
    dest: "{{ sap_netweaver_ha_pacemaker_fencing_device.password_file }}"
    content: 'echo "{{ sap_netweaver_ha_pacemaker_fencing_device.pwd }}"'
    mode: 0700
  when:
    - sap_netweaver_ha_pacemaker_fencing_device.password_file
  
- name: Create stonith device without host mapping
  command: >
    pcs stonith create {{ sap_netweaver_ha_pacemaker_fencing_device.name }} {{ sap_netweaver_ha_pacemaker_fencing_device.type }}
    ipaddr={{ sap_netweaver_ha_pacemaker_fencing_device.ip }} login={{ sap_netweaver_ha_pacemaker_fencing_device.user }}
    {{ password_frag }} pcmk_host_list={{ sap_netweaver_ha_pacemaker_fencing_device.pcmk_host_list }} {{ sap_netweaver_ha_pacemaker_fencing_device.custom_options | default() }} monitor interval=30
  when:
    - sap_netweaver_ha_pacemaker_fencing_device.type != "fence_azure_arm"
    - sap_netweaver_ha_pacemaker_fencing_device.pcmk_host_list is defined
  register: stonith_device
  changed_when: "'error' not in stonith_device.stdout"
  run_once: true

- name: Create stonith device with host mapping
  command: >
    pcs stonith create {{ sap_netweaver_ha_pacemaker_fencing_device.name }} {{ sap_netweaver_ha_pacemaker_fencing_device.type }}
    ipaddr={{ sap_netweaver_ha_pacemaker_fencing_device.ip }} login={{ sap_netweaver_ha_pacemaker_fencing_device.user }}
    {{ password_frag }} pcmk_host_map={{ sap_netweaver_ha_pacemaker_fencing_device.pcmk_host_map }} {{ sap_netweaver_ha_pacemaker_fencing_device.custom_options | default() }} op monitor interval=30
  when:
    - sap_netweaver_ha_pacemaker_fencing_device.type != "fence_azure_arm"
    - sap_netweaver_ha_pacemaker_fencing_device.pcmk_host_map is defined
  register: stonith_device
  changed_when: "'error' not in stonith_device.stdout"
  run_once: true

